---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
stringData:
  username: {{ .Values.username }}
  password: {{ .Values.password }}
  servicePort: {{ .Values.servicePort | quote }}
  backend: {{ .Values.backend }}
  serviceName: {{ .Values.serviceName }}

