{{ if .Values.secret.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backendType }}
  namespace: {{ .Release.Namespace }}
stringData:
  username: {{ .Values.secret.username }}
  password: {{ .Values.secret.password }}
  servicePort: {{ .Values.secret.servicePort | quote }}
  backend: {{ .Values.secret.backend }}
  serviceName: {{ .Values.backendType }}-csp-svc
{{- end }}

