---
apiVersion: storage.hpe.com/v1
kind: HPECSIDriver
metadata:
  name: csi-driver
spec:
  # Default values for hpe-csi-storage.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # Default values copied from <project_dir>/helm-charts/hpe-csi-driver/values.yaml
  images:
    # csi-driver
    csiDriverImage: hpestorage/csi-driver:v1.1.0
    # csp-hpe
    cspImage: dockerciuser/hpe_3par_primera_csp:test  
  
  # image pull policy for all images in csi deployment
  imagePullPolicy: 'Always'

  # HPE backend storage type (nimble, primera3par)
  backendType: primera3par

  secret:
    # parameters for nimble
    create: true
    backend: 192.168.1.1
    username: admin
    password: admin
    servicePort: "8080"

  # flavor
  flavor: kubernetes

  # log level for all csi driver components
  logLevel: info

  ## For creating the StorageClass automatically:
  storageClass:
    create: true

    ## Set StorageClass as the default StorageClass
    ## Ignored if storageClass.create is false
    defaultClass: false

    ## Set a StorageClass name
    ## Ignored if storageClass.create is false
    name: hpe-standard
    # Enable volume resize
    ## Ignored if storageClass.create is false
    allowVolumeExpansion: true
    # Default storage class parameters
    parameters:
      fsType: ext4
      volumeDescription: "Volume created by the HPE CSI Driver for Kubernetes"
      accessProtocol: "iscsi"

  ## For controlling automatic iscsi/multipath package installation (default: false)
  disableNodeConformance: false

