# Configuration to deploy the HPE 3PAR Primera Storage CSP service
#
# example usage: kubectl create -f <this_file>

---

#######################################
############  CSP Service  ############
#######################################

kind: Service
apiVersion: v1
metadata:
  name: primera3par-csp-svc
  namespace: kube-system
  labels:
    app: primera3par-csp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: primera3par-csp

---

##########################################
############  CSP Deployment  ############
##########################################

kind: Deployment
apiVersion: apps/v1
metadata:
  name: primera3par-csp
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: primera3par-csp
  replicas: 1
  template:
    metadata:
      labels:
        app: primera3par-csp
    spec:
      priorityClassName: system-cluster-critical
      containers:
        - name: primera3par-csp
          image: hpestorage/hpe3parprimera-csp:v1.0.0
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: log-dir
              mountPath: /var/log
      volumes:
        - name: log-dir
          hostPath:
            path: /var/log
